### ISSUE TITLE
"Lemma Match" is not working after exporting 

### ISSUE THREAD

**Issue by avinashreddy07** [CODAIT/nlp-editor#102] opened 2022-09-20 12:04 UTC
I observed that lemma match is working properly on nle-editor(UI), but when I export the extractor and run the extractor zip in my custom code, results are not coming (empty dictionary). Is this the know issue. Attaching my findings.

<img width="843" alt="image (1)" src="https://user-images.githubusercontent.com/25619001/191252379-659ee53f-1c0b-405c-84ce-b09f877c8919.png">

[Lemma.zip](https://github.com/CODAIT/nlp-editor/files/9607373/Lemma.zip)

**Comment by laurachiticariu** [comment] 2022-09-27 18:12
We are not able to reproduce this. Can you please provide details on what text and what language you use at runtime? The language used at runtime hasd to match the language used at design time.

**Comment by laurachiticariu** [comment] 2022-10-21 20:59
Fix will be in v0.4.0

**Comment by laurachiticariu** [comment] 2022-10-21 21:08
@avinashreddy07 we will need reproduction steps for this issue.

**Comment by laurachiticariu** [comment] 2022-10-28 19:04
Closing as nor reproducible. If you can reproduce, please re-open with reproduction steps.

**Closed by laurachiticariu** 2022-10-28 19:04 UTC
Labels: bug, low-priority
